export interface DirectoryItem {
  id: string
  name: string
  path: string
  type: "page" | "component" | "api" | "config" | "asset"
  status: "complete" | "in-progress" | "pending" | "error"
  description: string
  dependencies: string[]
  lastModified: Date
  size?: string
  testStatus: "passed" | "failed" | "pending" | "not-tested"
  accessibility: "compliant" | "partial" | "non-compliant"
  performance: number // 0-100 score
}

export interface DirectorySection {
  id: string
  title: string
  description: string
  items: DirectoryItem[]
  totalItems: number
  completedItems: number
  criticalPath: boolean
}

export const adminDirectoryData: DirectorySection[] = [
  {
    id: "core-pages",
    title: "Core Application Pages",
    description: "Main user-facing pages and core functionality",
    criticalPath: true,
    totalItems: 12,
    completedItems: 10,
    items: [
      {
        id: "home",
        name: "Home Page",
        path: "/",
        type: "page",
        status: "complete",
        description: "Landing page with hero section and navigation",
        dependencies: ["layout", "theme-provider"],
        lastModified: new Date("2024-01-15"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 95,
      },
      {
        id: "quiz-categories",
        name: "Quiz Categories",
        path: "/categories",
        type: "page",
        status: "complete",
        description: "Browse and select quiz categories",
        dependencies: ["card", "badge", "button"],
        lastModified: new Date("2024-01-14"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 92,
      },
      {
        id: "quiz-play",
        name: "Quiz Gameplay",
        path: "/quiz/play",
        type: "page",
        status: "complete",
        description: "Interactive quiz gameplay interface",
        dependencies: ["progress", "timer", "question-card"],
        lastModified: new Date("2024-01-13"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 88,
      },
      {
        id: "leaderboard",
        name: "Leaderboard",
        path: "/leaderboard",
        type: "page",
        status: "complete",
        description: "Global and category leaderboards",
        dependencies: ["table", "avatar", "badge"],
        lastModified: new Date("2024-01-12"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 90,
      },
      {
        id: "profile",
        name: "User Profile",
        path: "/profile",
        type: "page",
        status: "in-progress",
        description: "User profile and statistics",
        dependencies: ["avatar", "tabs", "chart"],
        lastModified: new Date("2024-01-11"),
        testStatus: "pending",
        accessibility: "partial",
        performance: 85,
      },
    ],
  },
  {
    id: "admin-features",
    title: "Administrative Features",
    description: "Admin-only functionality and management tools",
    criticalPath: true,
    totalItems: 8,
    completedItems: 6,
    items: [
      {
        id: "dashboard",
        name: "Admin Dashboard",
        path: "/dashboard",
        type: "page",
        status: "complete",
        description: "GitHub project approval workflow dashboard",
        dependencies: ["project-card", "modal", "status-badge"],
        lastModified: new Date("2024-01-15"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 93,
      },
      {
        id: "design-system",
        name: "Design System",
        path: "/design-system",
        type: "page",
        status: "complete",
        description: "Component library and design tokens",
        dependencies: ["all-ui-components"],
        lastModified: new Date("2024-01-14"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 91,
      },
      {
        id: "sitemap",
        name: "Site Architecture",
        path: "/sitemap",
        type: "page",
        status: "complete",
        description: "Visual sitemap and flow diagrams",
        dependencies: ["flow-diagram", "wireframe"],
        lastModified: new Date("2024-01-13"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 89,
      },
      {
        id: "cicd",
        name: "CI/CD Pipeline",
        path: "/cicd",
        type: "page",
        status: "complete",
        description: "Build and deployment monitoring",
        dependencies: ["pipeline-status", "logs-modal"],
        lastModified: new Date("2024-01-12"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 87,
      },
    ],
  },
  {
    id: "ui-components",
    title: "UI Component Library",
    description: "Reusable components and design system elements",
    criticalPath: false,
    totalItems: 25,
    completedItems: 23,
    items: [
      {
        id: "button",
        name: "Button Component",
        path: "/components/ui/button",
        type: "component",
        status: "complete",
        description: "Primary button component with variants",
        dependencies: ["class-variance-authority"],
        lastModified: new Date("2024-01-10"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 98,
      },
      {
        id: "card",
        name: "Card Component",
        path: "/components/ui/card",
        type: "component",
        status: "complete",
        description: "Flexible card container component",
        dependencies: ["utils"],
        lastModified: new Date("2024-01-10"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 97,
      },
      {
        id: "emotional-card",
        name: "Emotional Card",
        path: "/components/ui/emotional-card",
        type: "component",
        status: "complete",
        description: "AlignUI emotional design card component",
        dependencies: ["card", "design-tokens"],
        lastModified: new Date("2024-01-09"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 94,
      },
    ],
  },
  {
    id: "api-routes",
    title: "API Routes & Services",
    description: "Backend services and API endpoints",
    criticalPath: true,
    totalItems: 6,
    completedItems: 4,
    items: [
      {
        id: "quiz-generator",
        name: "Quiz Generator Service",
        path: "/lib/quiz-generator",
        type: "api",
        status: "complete",
        description: "AI-powered quiz question generation",
        dependencies: ["openai-api"],
        lastModified: new Date("2024-01-08"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 86,
      },
      {
        id: "github-integration",
        name: "GitHub API Integration",
        path: "/lib/github-workflow-data",
        type: "api",
        status: "complete",
        description: "GitHub project workflow integration",
        dependencies: ["github-api"],
        lastModified: new Date("2024-01-07"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 84,
      },
    ],
  },
  {
    id: "configuration",
    title: "Configuration & Setup",
    description: "Project configuration and build setup",
    criticalPath: true,
    totalItems: 10,
    completedItems: 10,
    items: [
      {
        id: "tailwind-config",
        name: "Tailwind Configuration",
        path: "/tailwind.config.js",
        type: "config",
        status: "complete",
        description: "Tailwind CSS configuration with AlignUI tokens",
        dependencies: ["design-tokens"],
        lastModified: new Date("2024-01-06"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 100,
      },
      {
        id: "global-styles",
        name: "Global Styles",
        path: "/app/globals.css",
        type: "config",
        status: "complete",
        description: "Global CSS with emotional design system",
        dependencies: ["tailwind-config"],
        lastModified: new Date("2024-01-05"),
        testStatus: "passed",
        accessibility: "compliant",
        performance: 96,
      },
    ],
  },
]

export const systemHealthMetrics = {
  overallHealth: 92,
  criticalPathCompletion: 95,
  testCoverage: 87,
  accessibilityScore: 94,
  performanceAverage: 91,
  lastFullScan: new Date("2024-01-15T10:30:00Z"),
  totalFiles: 61,
  completedFiles: 53,
  pendingFiles: 6,
  errorFiles: 2,
}

export const deploymentChecklist = [
  {
    id: "code-quality",
    name: "Code Quality Check",
    status: "complete",
    description: "ESLint, Prettier, TypeScript validation",
    critical: true,
  },
  {
    id: "test-coverage",
    name: "Test Coverage",
    status: "complete",
    description: "Unit tests, integration tests, E2E tests",
    critical: true,
  },
  {
    id: "accessibility",
    name: "Accessibility Audit",
    status: "complete",
    description: "WCAG 2.1 AA compliance check",
    critical: true,
  },
  {
    id: "performance",
    name: "Performance Optimization",
    status: "in-progress",
    description: "Lighthouse audit, Core Web Vitals",
    critical: true,
  },
  {
    id: "security",
    name: "Security Scan",
    status: "pending",
    description: "Vulnerability assessment, dependency audit",
    critical: true,
  },
  {
    id: "browser-testing",
    name: "Cross-Browser Testing",
    status: "complete",
    description: "Chrome, Firefox, Safari, Edge compatibility",
    critical: false,
  },
]
