import { MessageCircle, Heart, Target, PiggyBank, Home, Briefcase, Smile, Users } from "lucide-react"

export const focusAreas = [
  {
    id: "communication",
    title: "Communication",
    description: "Explore your communication styles, listening skills, and how you express needs and emotions.",
    icon: MessageCircle,
    color: "from-blue-500 to-cyan-500",
    questions: 5,
    avgTime: "10 min",
  },
  {
    id: "finances",
    title: "Finances",
    description: "Align on your financial goals, spending habits, and long-term money management.",
    icon: PiggyBank,
    color: "from-green-500 to-emerald-500",
    questions: 5,
    avgTime: "15 min",
  },
  {
    id: "future-goals",
    title: "Future Goals",
    description: "Discuss your personal and shared aspirations for the next 1, 5, and 10 years.",
    icon: Target,
    color: "from-purple-500 to-violet-500",
    questions: 5,
    avgTime: "12 min",
  },
  {
    id: "intimacy",
    title: "Intimacy & Connection",
    description: "Deepen your emotional and physical connection and understanding of each other's needs.",
    icon: Heart,
    color: "from-red-500 to-rose-500",
    questions: 5,
    avgTime: "10 min",
  },
  {
    id: "household",
    title: "Household & Chores",
    description: "Find balance and fairness in managing your shared living space and responsibilities.",
    icon: Home,
    color: "from-orange-500 to-amber-500",
    questions: 5,
    avgTime: "8 min",
  },
  {
    id: "career",
    title: "Career & Ambitions",
    description: "Support each other's professional growth and align on work-life balance.",
    icon: Briefcase,
    color: "from-indigo-500 to-blue-500",
    questions: 5,
    avgTime: "10 min",
  },
  {
    id: "leisure",
    title: "Leisure & Fun",
    description: "Discover new ways to enjoy your time together and pursue shared hobbies.",
    icon: Smile,
    color: "from-pink-500 to-fuchsia-500",
    questions: 5,
    avgTime: "8 min",
  },
  {
    id: "family-friends",
    title: "Family & Friends",
    description: "Navigate relationships with your extended social circles and set healthy boundaries.",
    icon: Users,
    color: "from-teal-500 to-cyan-500",
    questions: 5,
    avgTime: "12 min",
  },
]
